ВСК-27 Сваггер документация для courses
QActf/backend pull request #71
Opened 2024-04-25 04:16 UTC by NECROshizo

- Добавлены summary и description в описание хендлеров
- Отредактированы в документации наборы ошибок
- Удалены дублирующие хендлеры
- Минорный рефакторинг

2024-04-25 05:54 UTC, D-Abramoc approved these changes

2024-04-25 06:16 UTC, MikhailDevW commented
Добавь плиз остальных коллег для ревью - меня и Антона.
По ПР есть нюансы.

2024-04-25 06:34 UTC, MikhailDevW requested changes
И необходимо сквошнуть (слить в один) все коммиты чтобы в ветке девелоп не было навала разных комитов при разработке в ветке.

2024-04-25 06:34 UTC, MikhailDevW commented on app/api/endpoints/course.py
> +                                           PATCH_COURSE)
Не по PEP. Странно что линтер это пропустил. 
И я кажись жоска косякнул когда линтер заливал, там есть очепятка кажется - нолик лишний в строке стоит, его бы убрать и знаово прогнать.

2024-04-25 06:34 UTC, MikhailDevW commented on app/api/endpoints/course.py
>  from app.api_docs_responses.utils_docs import \
Обратный слеш

2024-04-25 06:34 UTC, MikhailDevW commented on app/api_docs_responses/course.py
> +
пепка

2024-04-25 06:37 UTC, MikhailDevW commented on app/api/endpoints/course.py
> +                                           PATCH_COURSE)
Это в файле pyproject.toml

2024-04-25 16:48 UTC, NECROshizo commented on app/api/endpoints/course.py
> +                                           PATCH_COURSE)
Да мне тоже нравится такая запись, НО
- Так было принято сделать до меня, общих документов по code-style я не нашел на этот проект, так что принимаю такой стиль как конвенциональный.
- Я не вижу здесь нарушения по PEP8(если это понимается под ПКП), если я неправ буду только рад если сошлетесь на нарушенное правило.
P.S. почему были выбраны именно такие параметры форматирования, что вы прописали в isort? И может стоит использовать сразу и pre-commit, раз вы решили составлять  code-style?

2024-04-25 16:50 UTC, NECROshizo commented on app/api_docs_responses/course.py
> +
Если пепка, это PEP8, то буду благодарен если сошлетесь какое правило это нарушает.

2024-04-25 16:57 UTC, NECROshizo commented
> И необходимо сквошнуть (слить в один) все коммиты, чтобы в ветке развиваться, не было навала разных комитов при разработке в ветке.

А можете пояснить, зачем это делать перед закрытием ПР, а не во время закрытия при вливание в develop(например при выборе в веб интерфейе "Squash and merge")?

2024-04-26 06:19 UTC, MikhailDevW commented
> > И необходимо сквошнуть (слить в один) все коммиты, чтобы в ветке развиваться, не было навала разных комитов при разработке в ветке.
> 
> А можете пояснить, зачем это делать перед закрытием ПР, а не во время закрытия при вливание в develop(например при выборе в веб интерфейе "Squash and merge")?

Можно забыть про это, посмотри что у нас в деве с коммитами (=

2024-04-27 07:32 UTC, MikhailDevW approved these changes
Заливаем (=

2024-04-27 07:33 UTC, MikhailDevW commented
Не забыть бы теперь скворшнуть коммиты (=

2024-04-27 15:49 UTC, merged