Psql
QActf/backend pull request #73
Opened 2024-05-01 20:17 UTC by D-Abramoc

Собирается контейнер постгрес.
Поправил тесты.

2024-05-01 21:57 UTC, MikhailDevW requested changes
Предложу еще сквошнуть все коммиты дабы не забыть потом про это при вливании.

2024-05-01 21:57 UTC, MikhailDevW commented on .github/workflows/main.yml
> +
А для чего отделять тут? Можно визуально отделить тесты на строке выше.

2024-05-01 21:57 UTC, MikhailDevW commented on alembic/env.py
> +# from app.core.config import settings
Зачем комментарии нести в другую ветку?

2024-05-01 21:57 UTC, MikhailDevW commented on alembic/env.py
> +    #     #     context.run_migrations()
Вот это тоже для чего так?

2024-05-01 21:57 UTC, MikhailDevW commented on alembic/env.py
>      asyncio.run(run_async_migrations())
Миграции сейас будут создаваться через алембик или запуском этого файла?

2024-05-01 21:57 UTC, MikhailDevW commented on infra/docker-compose.yml
> +    image: postgres
Указать бы версию.

2024-05-01 21:57 UTC, MikhailDevW commented on infra/docker-compose.yml
> +    container_name: web
будет же и фронт, может и назвать backend?

2024-05-01 21:57 UTC, MikhailDevW commented on tests/conftest.py
> +                                    create_async_engine)
Не по PEP

2024-05-01 21:57 UTC, MikhailDevW commented on tests/fixtures/user.py
> +            app=prepare_database,
Не по PEP - отступ 4 знака

2024-05-01 21:57 UTC, MikhailDevW commented on tests/fixtures/user.py
> +            'username': 'admin@admin.com',
Пеп

2024-05-01 21:57 UTC, MikhailDevW commented on app/core/config.py
>      database_url: str = "sqlite+aiosqlite:///./fastapi.db"
А вот это еще требуетя?

2024-05-01 23:21 UTC, D-Abramoc commented on .github/workflows/main.yml
> +
++

2024-05-01 23:21 UTC, D-Abramoc commented on alembic/env.py
> +# from app.core.config import settings
++

2024-05-01 23:22 UTC, D-Abramoc commented on alembic/env.py
> +    #     #     context.run_migrations()
++

2024-05-01 23:22 UTC, D-Abramoc commented on alembic/env.py
>      asyncio.run(run_async_migrations())
это уже не надо. удалил

2024-05-01 23:23 UTC, D-Abramoc commented on infra/docker-compose.yml
> +    image: postgres
подтянется latest

2024-05-01 23:24 UTC, D-Abramoc commented on infra/docker-compose.yml
> +    container_name: web
++

2024-05-01 23:25 UTC, D-Abramoc commented on tests/conftest.py
> +                                    create_async_engine)
++

2024-05-01 23:26 UTC, D-Abramoc commented on tests/fixtures/user.py
> +            app=prepare_database,
++

2024-05-01 23:27 UTC, D-Abramoc commented on tests/fixtures/user.py
> +            'username': 'admin@admin.com',
++

2024-05-01 23:39 UTC, D-Abramoc commented on app/core/config.py
>      database_url: str = "sqlite+aiosqlite:///./fastapi.db"
++

2024-05-03 06:53 UTC, MikhailDevW commented
- Добавить бы остальных участников для ревью.
- Забрать бы все изменнеия с ветки девелоп чтобы не было конфликтов.
- Я бы обозвал ветку более понятно для истории.

2024-05-03 06:59 UTC, MikhailDevW requested changes
Есть небольшие правки с моей точки зрения.

2024-05-03 06:59 UTC, MikhailDevW commented on app/models/user.py
> +    ]
Вот здесь это изменено, но в других местах проекта используется такой же код. При изменениии в одном месте придется менять и в другом. Лушче бы сделать один источник.

2024-05-03 06:59 UTC, MikhailDevW commented on app/schemas/user.py
см выше про один источник

2024-05-03 06:59 UTC, MikhailDevW commented on infra/docker-compose.yml
> +    image: postgres
Ну я бы указывал из-за того что может вдруг потом что-нибудь сломаться когда будет уже другая latest

2024-05-05 08:38 UTC, D-Abramoc commented on infra/docker-compose.yml
> +    image: postgres
++

2024-05-05 11:24 UTC, D-Abramoc commented on app/models/user.py
> +    ]
++

2024-05-05 11:24 UTC, D-Abramoc commented on app/schemas/user.py
++

2024-05-12 13:56 UTC, closed without merging

2024-05-12 13:57 UTC, D-Abramoc commented
Из этого ПР все забрано в новый