conftest
QActf/backend pull request #80
Opened 2024-05-10 12:34 UTC by D-Abramoc

* заменил sessionmaker на async_sessionmaker
* в фикстуре db_session для transaction применил метод get_raw_connection, в transaction.rollback() убрал await

В фикстуре создания клиента заменил TestClient на AsyncClient

Все респонзы сделал через await

Вынес определение ролей в файл app/core/constants.py Зафиксировал версию постгрес в docker-compose.yml

add services into cicd

2024-05-11 05:42 UTC, MikhailDevW commented
- Я бы назвал ПР и коммиты более читаемо, чтобы в истории ыло понятно что делалось и где что искать. Это для удобства и порядка в репе. Сейчас по ПР непонятно что тут делалось
- Изменены 59 файло и 1500 строк, однако судя ним эти изменения уже есть в ветке девелоп. Их необходимо забрать и тогда конфликты решатся и не будет столько изменений. Не видно что именно делалось в этом ПР.
- Добавить бы коллег для ревью.
- На данный момент ревью сделать нельзя

2024-05-11 05:43 UTC, MikhailDevW requested changes
Есть что исправить.

2024-05-12 13:52 UTC, D-Abramoc commented
> * Я бы назвал ПР и коммиты более читаемо, чтобы в истории ыло понятно что делалось и где что искать. Это для удобства и порядка в репе. Сейчас по ПР непонятно что тут делалось

* Более читаемо понятие растяжимое

> * Изменены 59 файло и 1500 строк, однако судя ним эти изменения уже есть в ветке девелоп. Их необходимо забрать и тогда конфликты решатся и не будет столько изменений. Не видно что именно делалось в этом ПР.

* я вмержил девелоп в свою ветку возникли конфликты. смержил это и есть забрать?

> * Добавить бы коллег для ревью.

* Ну кроме Кости я не знаю кто живой. Написал в телеге, кто откликнется добавлю

> * Если другой ПР уже не нужен, то его бы удалить.
> * На данный момент ревью сделать нельзя
* Очень полезное замечание. Было бы лучше написать, что сделать, чтобы ревью было можно сделать.

2024-05-12 13:56 UTC, D-Abramoc commented
> Есть что исправить.

Пойду что нибудь исправлю

2024-05-13 07:01 UTC, MikhailDevW commented
> Более читаемо понятие растяжимое
Любое название описывающее что делает данный ПР. Название conftest совсем не отражает сущности ПР.

> я вмержил девелоп в свою ветку возникли конфликты. смержил это и есть забрать?
когда идет работа над какой-то своей веткой, в главной ветке ( у нас девелоп) могут быть сделаны коммиты. Соответсвенно твоя ветка уже будет отставать от главной ветки. Сейчас по файлам в ПР видно что сделаны измеения которые уже есть в девелопе и в ПР их быть не должно. Перед ПР надо слить изменения из девелоп в свою ветку чтобы она стала актуальной.

> Очень полезное замечание. Было бы лучше написать, что сделать, чтобы ревью было можно сделать.
На данный момент судя по ПР изменения касаются 59 файлов и 1500 строк. Эти изменения все касаются переезда на постгрю? Судя по изменениям нет, а есть даже те которые уже влиты в девелоп. Среди такого количества трудно найти те изменения которые были сделаны для ПР. Например изменения с документацией и isort уже сделаны. Тут надо актуализировать свою ветку чтобы были актулаьные изменения касающиеся постгри.

2024-05-13 13:33 UTC, closed without merging

2024-05-13 13:33 UTC, D-Abramoc commented
Сделан новый ПР.