Feature/bck 36 pre commit
QActf/backend pull request #84
Opened 2024-05-19 19:51 UTC by NECROshizo

- Добавлены пре комит хуки
  - check-yaml проверка yaml
  - end-of-file-fixer  добавляет пустую строку в конце при необходимости
  - trailing-whitespace удаляет пробелы в конце строк
  - check-merge-conflict проверка на метки слияния
  - double-quote-string-fixer  " ===> '
 - Автоформотирования импортов isort
- flacke8 общая проверка + плагины
  - pep8-naming проверка имен переменных
  - flake8-isort доп проверка порядка импортов на всякий случай
  - flake8-broken-line проверка правильности переноса строк
  - flake8-bugbear потенциальные доработки в коде
 - добавлен pytest к хукам
 - пара ручных правок.
 - перенос всех конфигов в setup.cfg
 - в readme справка по использованию pre-commit

P.S. файлы интереса [.pre-commit-config.yaml](https://github.com/QActf/backend/compare/develop...feature/BCK-36_pre_commit#diff-63a9c44a44acf85fea213a857769990937107cf072831e1a26808cfde9d096b9), [setup.cfg](https://github.com/QActf/backend/compare/develop...feature/BCK-36_pre_commit#diff-fa602a8a75dc9dcc92261bac5f533c2a85e34fcceaff63b3a3a81d9acde2fc52), ручная правка на сырую строку [app/services/mail.py](https://github.com/QActf/backend/compare/develop...feature/BCK-36_pre_commit#diff-d80d5f96b0df7e0fd17230ba8c56eef65818818587d60cd69947ea54adf2a878)

2024-05-20 08:27 UTC, MikhailDevW requested changes
Годно. В проекте появляется порядок

2024-05-20 08:27 UTC, MikhailDevW commented on README.md
> +- Запустить конкретный хук: `poetry run pre-commit run <имя-хука>`
Я когда пришел в проект, как я понял все сразу запускалось и работало только в докере.
И там во флоу используется пипка. Тут поетри. С чем это связано и надо ли?
Дополнительно я думал а почему бы не сделать скрипт запуска проекта когда на машине он запускается и если есть питончик тос тавит виртуальное окружение, все зависимости и настраивает проект, включая пре-коммит, чтобы руками каждый раз этого не делать. На обсуждение.

2024-05-20 08:27 UTC, MikhailDevW commented on app/admin/authentication.py
>              strategy: JWTStrategy = get_jwt_strategy()
Этот файл трогался только для рефача однако тут отступы не 4 пробела.

2024-05-20 08:27 UTC, MikhailDevW commented on app/admin/authentication.py
>          return True
Тут и формы и токен. Странный файл....

2024-05-20 08:27 UTC, MikhailDevW commented on app/api/endpoints/register.py
>              raise HTTPException(
в этом файле тоже не 4 пробела отступы да и везде по проекту

2024-05-20 08:27 UTC, MikhailDevW commented on tests/test_group.py
> +        """Создание группы суперюзером/."""
слеш это опечатка?

2024-05-20 08:27 UTC, MikhailDevW commented on setup.cfg
> +[tool:pytest]
А вот тут для моего понимания обязательно писать tools.?? флейк и исорт без этого указания. Не будет так работать?

2024-05-22 13:01 UTC, D-Abramoc approved these changes
Я пока не совсем понял для чего это. Видимо это можно запустить перед коммитом и всякие мелкие штуки сами поправятся. Наверное норм

2024-05-26 17:57 UTC, NECROshizo commented on README.md
> +- Запустить конкретный хук: `poetry run pre-commit run <имя-хука>`
Нет, тут я свою памятку копировал и не углядел.

2024-05-26 17:58 UTC, NECROshizo commented on app/admin/authentication.py
>              strategy: JWTStrategy = get_jwt_strategy()
Эти строки мной не менялись. Так было самого начала, вообще странные артефакты постоянно встречаются.

2024-05-26 17:58 UTC, NECROshizo commented on app/admin/authentication.py
>          return True
да

2024-05-26 17:58 UTC, NECROshizo commented on app/api/endpoints/register.py
>              raise HTTPException(
да, но в этой строке не вижу проблем.

2024-05-26 17:58 UTC, NECROshizo commented on tests/test_group.py
> +        """Создание группы суперюзером/."""
Да, поправил.

2024-05-26 17:58 UTC, NECROshizo commented on setup.cfg
> +[tool:pytest]
Pytest согласно [документации](https://docs.pytest.org/en/stable/reference/customize.html#setup-cfg), все остальные разрешают так.
setup.cfg потому что pyproject.toml не поддерживается доживающим старичком flake8.

2024-05-26 18:02 UTC, NECROshizo commented
> Я пока не совсем понял для чего это. Видимо это можно запустить перед коммитом и всякие мелкие штуки сами поправятся. Наверное норм
Предполагается что инициализируются хуки `pre-commit install`, и после этого любой комит не будет исполнен пока не пройдет все тестирование как кодстайлом так и тестами. + авторформатеры вносят изменения. Это обычно делается в начале проекта, чтобы код был в едином стиле в дальнейшем.

2024-05-29 10:01 UTC, MikhailDevW approved these changes

2024-06-03 15:55 UTC, merged